### ISSUE TITLE
Incompatible with http > 4.0.0

### ISSUE THREAD

**Issue by jerko-culina** [drEnilight/vatlayer-ruby#1]
Sorry if this is not the right place for this!

I found out that vatlayer is incompatible with the newest http gem:

```
Bundler could not find compatible versions for gem "http":
  In snapshot (Gemfile.lock):
    http (= 4.1.1)

  In Gemfile:
    http (= 4.1.1)

    vatlayer was resolved to 0.3.2, which depends on
      http (~> 3.3.0)```

**Comment by drEnilight** [comment]
@jerko-culina  Hello. Sorry for the late response. 
`http` version was updated and now compatible with ~> 4.2.

P.S. Let me know if smth wrong.
